# Background and Review of literature {#sec2}

## Fiscal roots of inflation and debt decomposition {#sec2.1}

Hall and Sargent [-@hall1997; -@Hall2011] analyses government finances and decomposes debt-GDP of US into nominal interest rate, growth rate, inflation, primary deficit/surplus, and maturity structure of debt. Their study is an important precursor to the analysis of government finances and how debt is paid off, grown out or inflated away.

@COCHRANE201474 studies monetary policy with interest on reserves based on the fiscal theory of price level. He finds that monetary policy determines expected inflation and unexpected inflation is determined by expectations of future surpluses. @NBERw26090 analyses the combination of debt, surpluses and deficits, inflation, bond returns and growth rate that produce debt in each period. Using standard result from the fiscal theory and decomposing debt following asset pricing literature, they find that about half of the post-war variation in debt to GDP ratios corresponds to variation in expected future surpluses, and about half to expected growth-adjusted discount rates. A big message of their study is that discount rates matter a lot to understanding
debt dynamics, especially at the very low and very high frequencies. @Cochrane2021 study fiscal roots of inflation for US economy from 1947-2018 using linearized debt flow identities and vector autoregressions that measure each components and their responses. Their results show a greater role for discount rates in inflation accounting while surpluses have greater role in the variation in government debt levels. Their results show that rise in inflation contributes most to the decline in present value of surpluses followed by discount rates and growth rates. @Das2021 studies the fiscal financing components and how they affect the debt-to-GDP ratios for different sub-periods for the United States between 1942 and 2017. Their simple model of policy interaction and sub-period analysis shows that inflation and surplus/deficit play important role in debt in a fiscal regime whereas growth rates play major role in monetary regime.  

A large literature has established the overall superiority of combining linear forecasts [@granger1969; @granger1984]. The intuition underlying this finding is straightforward: combining forecasts achieves diversification gains –combinations of forecasts based on, say, different information sets, pools together different sources of information and, therefore, should result in lower expected loss (for example, lower expected error variance). @Dellas2018 study the macroeconomic and fiscal implications of inflation forecast errors using a new method that combines individual forecasts using time-varying coefficient estimation along with an alternative method based on neural nets. 

## Optimal Fiscal policy and Maturity Structure of Government Bonds {#sec2.2}
@Leeper2016 introduces a full maturity structure of government debt in general form
to derive the bond valuation equation and develop some intuition about the role that
maturity plays in the endowment economy in regime of "Active Fiscal policy Passive Monetary policy" (Regime F). They find that given the government budget constraint and a sequence of surpluses, discount factor and maturity structure determines the expected present value of surpluses. If primary surpluses are given, an unanticipated shortening of maturity of bonds held by the public would, by raising the value of outstanding debt, reduce the current price level [@COCHRANE201474; @Leeper2016].

@COCHRANE201474 in their model of fiscal theory of price level illustrate the role of changing maturity structure on inflation in a constant endowment economy. Their model shows that the government that issues one and two period nominal bonds at the beginning of time period yields price level in period two and also that the term structure of interest rate is dependent on the maturity structure of the bonds. However, Ricardian equivalence in regime M (Active Monetary policy Passive Fiscal policy) makes the maturity structure of debt irrelevant for inflation [@Leeper2016]. 

Introduction of maturity structure gives additional channel through which debt can be revalued. Unlike the case with one period debt where fiscal action resulted only in one period price level jumps, long term bonds in model reflect the expected inflation over the entire duration of debt and can result in drawn out inflation. A maturity structure makes the value of debt depend on the entire expected path of nominal interest rates. This gives monetary policy an expanded role in debt stabilization, allowing expected future monetary policy to affect the value of current debt. [@COCHRANE201474; @Cochrane2021; @Leeper2016].

In the context of optimal policy, textbook response  to an increase in government debt is simple—monetary policy should actively target inflation, and fiscal policy should smooth taxes while ensuring debt sustainability although such policy prescriptions presupposes  the ability of the government to commit [@LEEPER2021600]. @Leeper2016 studies the role inflation surprises play in optimal policy in a simple
endowment economy with a geometrically declining maturity structure. Their model of an endowment economy with time inconsistent Ramsey policy and a costless inflation shows that bonds with maturity of more than one period can produce multiple inflation paths that satisfy government debt valuation condition. @LEEPER2021600 assumes time-consistent policy making and assesses the importance of both debt maturity and the level of debt for the resulting equilibrium and find that (i) The temptation to use inflation surprises to stabilize debt grows with the level of debt and shrinks with the average maturity of that debt and thus equilibrium inflationary bias problem can be significantly lower with longer maturity debt ; (ii) The response to shocks is radically different under discretion vs. commitment and depends crucially on the level and maturity of government debt and (iii) Allowing the policy maker to choose the relative proportions of short- versus long-term debt as part of the time- consistent policy problem provides the current policy maker with a means to influence the pace at which a given stock of debt is reduced in the future.

# Research Gap and Research Objectives
## Research Gap
The literature on government finances and debt decomposition is relatively scarce and nascent especially in the context of emerging economies and high debt countries. To the best of our knowledge @das2021inflation is the only study that undertake a debt decomposition analysis for India using security level data. In the global context, @NBERw26090 and @betty2019 are the only studies that analyse decomposition. Given the dearth of studies undertaking debt decomposition and the relevance of growing public debt, this study attempts to undertake a debt decomposition analysis for high debt and low debt countries to identify fiscal components of public debt. 

Inflation as a fiscal phenomenon is of relatively new origin starting from the works of @sargent1981 and @Leeper1991. @Cochrane2021 uses asset pricing techniques to develop linearized identities to find the role of fiscal components in inflation accounting for US economy. Such an analysis , although purely measuremental will be interesting in the Indian context with rising public debt. Extending the framework to calculate the inflation forecast errors and comparing the inflation forecasts from combination forecasting methods can offer fresh insights on the role of forecast errors of inflation on public debt.

The role of maturity structure of government bonds in the context of optimal fiscal policy in a Ramsey setting has been analysed by many including @sims2013, @Leeper2016, and @Cochrane2021. All the above studies incorporate a geometric declining maturity structure of the long term bonds. We seek to identify the optimal bonds a fiscal authority should supply in the context of optimal fiscal policy by building a New-Keynesian model.

## Research Objectives
With this background, we would first identify fiscal components of government debt and inflation using a asset style decomposition. We would then calculate inflation forecast errors from the VAR approach as well as combination forecasts and compare them. Finally, we build a New-Keynesian model with long term government bonds and identify the optimum maturity of bonds in an optimal fiscal policy context In summary, our objectives are as follows:

1. Understand the fiscal components of government debt for high debt and low debt countries
1. Identify the fiscal components of inflation for India and compare the inflation forecast errors
1. Identify the optimum maturity bond structure for optimal fiscal policy 





