# Introduction {#sec1}

Since the Global Financial crisis (GFC) of 2007-08, most countries have experienced unprecedented rise in Debt to GDP ratio. The onset of Covid-19 has further aggravated government borrowing as countries across the globe have been borrowing heavily to combat the pandemic. The growth in debt levels in most advanced economies are higher than their World War II levels. The ratio of government debt to GDP is projected to rise by almost 20 percentage points by the end of 2022 across the OECD countries. Public debt ratios could turn out even higher than projected, given the still considerable uncertainty about the full economic impact of the crisis, the need for additional support measures and the possible realization of contingent liabilities such as loan guarantees. This unprecedented rise in debt levels have raised concerns over government debt sustainability and fiscal deficits of late. 

Conventional macroeconomic models carefully specify the connection of monetary policy to the evolution of the price level, while ordinarily leaving the government budget constraint and evolution of the stock of government debt entirely hidden[@Sims1999]. The fiscal theory is a complement to, rather than a substitute for, conventional views of price-level determination [@Leeper2016]. Since the study of @sargent1981 economists have increasingly begun to realise that fiscal policy is as important as monetary policy in the determination of price level [@Sims1999]. The analysis of government debt, surpluses and their decomposition are itself interesting in present times where governments across the world are running large deficits to combat the Covid-19 pandemic.  

In dynamic models, macroeconomic policies have two fundamental tasks to achieve: determine the price level and stabilize debt. These tasks can be achieved by either “Active Fiscal Policy Passive Monetary Policy” or “Active Monetary Policy Passive Fiscal Policy”^[The classification is due to @Leeper1991]. The combination of active monetary and passive fiscal policies or the policy regime of “monetary dominance” delivers the usual monetarist/new Keynesian setup in which monetary policy can target inflation and fiscal policy exhibits Ricardian equivalence. The fiscal theory of price level is a regime of “fiscal dominance” wherein passive monetary and active fiscal policies gives fiscal policy important effects on inflation, while monetary policy ensures that debt is stable. @Leeper2016 identifies important characteristics for these class of models featuring monetary policy, maturity structure for nominal government debt, taxes and government expenditures and government budget identity - a prominent role for nominal government debt revaluations and its effect through surprise changes in inflation and bond prices, possible interactions between monetary and fiscal policies to increase nominal wealth, aggregate demand and price level, importance of expectations of fiscal policy in determination of price level and debt management policies for equilibrium dynamics.  

The real value of nominal debt equals the present value of real primary surpluses. This is a part of standard New Keynesian model according to which surplus adjusts to the change in inflation. *The fiscal theory of price level* argues that it is price level that adjusts such that real value of nominal government debt is equal to the present value of future primary surpluses. Surpluses, though often out looked in most models are crucial in conduct of monetary policy as it drives the inflation path desired by the central banks. Thus fiscal theory is an alternative theory to conventional monetarist theories of price level determination.  

The evolution of ratio of debt to GDP ratio is determined by the government’s budget constraint. Specifically, debt to GDP ratio is affected by four components: nominal interest rate, inflation, growth and primary surplus. Identifying financing component of debt or debt decomposition is extremely relevant at a time when most of the nations are facing fiscal stress. Whether or not the governments should reduce their debt levels is an important policy issue. Although, @blanchard2019 argues that as long as interest on debt remains lower than growth rate, the ratio of debt to GDP decreases over time, economists all over the world are dubious about a potential debt crisis. We cannot know for sure about the debt crisis in future, but the lessons from history captured by the debt-decomposition calculations can help in learning how the past variation in debt to GDP ratio were resolved and how debts are resolved on average [@NBERw26090]. Growth-adjusted interest rate affects the debt limit by increasing the value of debt  for a lower interest rate [@betty2019]. Moreover, the expectations underlying the value of debt are a central part of many macroeconomic models.  

Inflation as mentioned above is an important component in the value of government debt. Higher inflation devalues nominal government debt and  must therefore correspond to lower surplus/GDP ratios, lower GDP growth, or higher discount rates for government debt.  @Cochrane2021 studies responses to each component using Vector Autoregressions (VAR) and finds that a 1\% shock to inflation corresponds to a 1.6\% decline in the present
value of surpluses. @NIEMANN20131097 find that the desire to inflate away the debt burden leads to large and persistent movements in inflation which are absent under commitment. Fiscal responses such as transfers are more inflationary in the fiscal regime than monetary regime. Forecasts of inflation also affect the cost of short-term and long-term government borrowing and, thus, the level and dynamics of public debt. An under appreciated dimension of inflation unpredictability concerns asset pricing. For assets with a fixed nominal rate of return (such as government bonds), unexpected movements in inflation (inflation forecast errors) generate movements in the realized rate of return [@Dellas2018]. This necessitates the accuracy of inflation forecasts for policy analysis. Following @Dellas2018 this study employs a new empirical strategy to improve the accuracy of inflation forecasts and quantify the importance of forecast errors on the value of debt decomposition.  

As characterized by @Leeper2016, maturity structure of nominal government bonds is another important pillar of the fiscal theory. Changes in the maturity composition of debt operate through impacts on the size and composition of private wealth. Such changes can affect the macro economy, even if they do not entail changing the overall size of the debt. Though optimal policy analysis in conventional monetary-fiscal policy analysis assigns monetary authority the task of controlling inflation and fiscal authority the task of fiscal sustainability, @sims2013 argues that government that can issue long term nominal bonds can stabilize debt through variation in bond prices. On the context of Ramsey problem, @faraglia2013, @leeper2013inflation, @Leeper2016, and @sheedy2014 find that the consensus policy assignment of use of inflation to stabilize debt being negligible remains largely optimal. 

Summarizing, this study will do a debt decomposition analysis for selected group of countries and identify the components that drive debt in each group of country. Given that inflation is a major driver of debt, we subsequently identify inflation as a fiscal phenomenon and do forecast evaluation of inflation. Finally, the study attempts to find the optimal maturity structure of long term nominal bonds in a optimal fiscal policy framework.

